name:                cqhttp
version:             0.1.0.0
github:              t532/cqhttp-haskell-sdk
license:             MIT
author:              t532
maintainer:          t532@foxmail.com
copyright:           2020 t532

extra-source-files:
- README.md

synopsis:            Simple typed interface to CoolQ HTTP API.
category:            Web
description:         Please see the README on GitHub at <https://github.com/t532/cqhttp#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- cryptonite
- http-types
- lifted-async
- mtl
- req
- scientific
- scotty
- template-haskell
- text
- time
- unordered-containers

library:
  source-dirs: src

tests:
  cqhttp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cqhttp
